# Generated by Django 5.0.13 on 2025-03-24 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_author_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 25, 13, 44, 33, 214391, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
